# Generated by Django 3.0.6 on 2020-06-24 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
